version: '3'
services:

  frontend-react:
    container_name: frontend-react-app
    build: ./FrontEnd-react
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
        reservations:
          cpus: '0.05'
          memory: 100M

  mysql_db:
    image: mysql
    container_name: mysql_DB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=vaibhav
      - MYSQL_DATABASE=my-db
      - MYSQL_USER=vaibhav
      - MYSQL_PASSWORD=vaibhav
    ports:
      - "3001:3306"
    # volumes:
    #   - ./init:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 200M
  

  express:
    container_name: ExpressJS_Backend
    build: ./ExpressJS
    environment:
      - MONGO_DB_URL=<<MONGODBURL GOES HERE>>
      - PORT=5000
      - SQLPORT=3001
      - HOST=172.20.5.39
      - USERNAME=vaibhav
      - PASSWORD=vaibhav
      - DB=my-db
      - DJANGOPORT=8000
      - DJHOST=localhost
    ports:
      - '5000:5000'
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '0.05'
          memory: 50M


  django:
    container_name: Django_ngram
    build: ./django
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
        reservations:
          cpus: '0.05'
          memory: 100M

  


