version: '3.6'

services:
  db:
    image: mysql
    container_name: mysql_DB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=vaibhav
      - MYSQL_DATABASE=my-db
      - MYSQL_USER=vaibhav
      - MYSQL_PASSWORD=vaibhav
    ports:
      - "3000:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 200M
